### ISSUE TITLE
unknown error <class 'RuntimeError'>: invalid vectorizer config: Connection error.

### ISSUE THREAD

**Issue by z-x-x136** [OpenSPG/KAG#347]
### Search before asking

- [x] I had searched in the [issues](https://github.com/OpenSPG/KAG/issues?q=is%3Aissue) and found no similar issues.

### Operating system information

Windows

### What happened

![Image](https://github.com/user-attachments/assets/3a119c78-ad77-4d97-97a4-20bcde5fbf51)

Ollama Vector Configuration docker-compose.yml

### How to reproduce

http://host.docker.internal:11435/v1
http://127.0.0.1:11435/v1
http://172.27.208.1:11435/v1
I tried, but I couldn't solve the problem.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by z-x-x136** [comment]
![Image](https://github.com/user-attachments/assets/0868f1bd-e72e-4708-8299-0c5d8e6a2c08)ollama starts normally

**Comment by z-x-x136** [comment]
curl "http://127.0.0.1:11435/v1/embeddings" -d "{ \"model\": \"bge-m3\", \"input\": [ \"work\" ] }"
ok

**Comment by z-x-x136** [comment]
My problem is with the proxy network inside the container, which can be solved by configuring compose.yaml (see figure)

![Image](https://github.com/user-attachments/assets/635ba49d-3e39-4d40-9033-d3a4c41e1325)
![Image](https://github.com/user-attachments/assets/248c7cc1-80a5-4f76-a038-e991c0949709)

**Comment by ThiruRJST** [comment]
How did you solve this issue?
I'm trying to use same ollama vectorizer and copy pasted the given config in documentation to my example_config.yaml
But raised the following error:
```
Done initialize project config with host addr http://127.0.0.1:8887 and project_id 1
No config found.
Error: invalid vectorizer config: RetryError[<Future at 0x7d6499d89360 state=finished raised NotImplementedError>]
```

My example_config.yaml:
```
#------------project configuration start----------------#
openie_llm: &openie_llm
  base_url: http://localhost:11434/
  model: qwen2.5:3b
  type: ollama

chat_llm: &chat_llm
  base_url: http://localhost:11434/
  model: qwen2.5:3b
  type: ollama

vectorize_model: &vectorize_model
  api_key: EMPTY
  base_url: http://host.docker.internal:11434/v1
  model: bge-m3
  type: openai
  vector_dimensions: 1024


log:
  level: INFO

project:
  biz_scene: default
  host_addr: http://127.0.0.1:8887
  id: "1"
  language: en
  namespace: CUAD
#------------project configuration end----------------#

#------------kag-builder configuration start----------------#
kag_builder_pipeline:
  chain:
    type: unstructured_builder_chain # kag.builder.default_chain.DefaultUnstructuredBuilderChain
    extractor:
      type: schema_free_extractor # kag.builder.component.extractor.schema_free_extractor.SchemaFreeExtractor
      llm: *openie_llm
      ner_prompt:
        type: default_ner # kag.builder.prompt.default.ner.OpenIENERPrompt
      std_prompt:
        type: default_std # kag.builder.prompt.default.std.OpenIEEntitystandardizationdPrompt
      triple_prompt:
        type: default_triple # kag.builder.prompt.default.triple.OpenIETriplePrompt
    reader:
      type: dict_reader # kag.builder.component.reader.dict_reader.DictReader
    post_processor:
      type: kag_post_processor # kag.builder.component.postprocessor.kag_postprocessor.KAGPostProcessor
    splitter:
      type: length_splitter # kag.builder.component.splitter.length_splitter.LengthSplitter
      split_length: 100000
      window_length: 0
    vectorizer:
      type: batch_vectorizer # kag.builder.component.vectorizer.batch_vectorizer.BatchVectorizer
      vectorize_model: *vectorize_model
    writer:
      type: kg_writer # kag.builder.component.writer.kg_writer.KGWriter
  num_threads_per_chain: 1
  num_chains: 16
  scanner:
    type: 2wiki_dataset_scanner # kag.builder.component.scanner.dataset_scanner.MusiqueCorpusScanner
#------------kag-builder configuration end----------------#

#------------kag-solver configuration start----------------#
search_api: &search_api
  type: openspg_search_api #kag.solver.tools.search_api.impl.openspg_search_api.OpenSPGSearchAPI

graph_api: &graph_api
  type: openspg_graph_api #kag.solver.tools.graph_api.impl.openspg_graph_api.OpenSPGGraphApi

exact_kg_retriever: &exact_kg_retriever
  type: default_exact_kg_retriever # kag.solver.retriever.impl.default_exact_kg_retriever.DefaultExactKgRetriever
  el_num: 5
  llm_client: *chat_llm
  search_api: *search_api
  graph_api: *graph_api

fuzzy_kg_retriever: &fuzzy_kg_retriever
  type: default_fuzzy_kg_retriever # kag.solver.retriever.impl.default_fuzzy_kg_retriever.DefaultFuzzyKgRetriever
  el_num: 5
  vectorize_model: *vectorize_model
  llm_client: *chat_llm
  search_api: *search_api
  graph_api: *graph_api

chunk_retriever: &chunk_retriever
  type: default_chunk_retriever # kag.solver.retriever.impl.default_fuzzy_kg_retriever.DefaultFuzzyKgRetriever
  llm_client: *chat_llm
  recall_num: 10
  rerank_topk: 10

kag_solver_pipeline:
  memory:
    type: default_memory # kag.solver.implementation.default_memory.DefaultMemory
    llm_client: *chat_llm
  max_iterations: 3
  reasoner:
    type: default_reasoner # kag.solver.implementation.default_reasoner.DefaultReasoner
    llm_client: *chat_llm
    lf_planner:
      type: default_lf_planner # kag.solver.plan.default_lf_planner.DefaultLFPlanner
      llm_client: *chat_llm
      vectorize_model: *vectorize_model
    lf_executor:
      type: default_lf_executor # kag.solver.execute.default_lf_executor.DefaultLFExecutor
      llm_client: *chat_llm
      force_chunk_retriever: true
      exact_kg_retriever: *exact_kg_retriever
      fuzzy_kg_retriever: *fuzzy_kg_retriever
      chunk_retriever: *chunk_retriever
      merger:
        type: default_lf_sub_query_res_merger # kag.solver.execute.default_sub_query_merger.DefaultLFSubQueryResMerger
        vectorize_model: *vectorize_model
        chunk_retriever: *chunk_retriever
  generator:
    type: default_generator # kag.solver.implementation.default_generator.DefaultGenerator
    llm_client: *chat_llm
    generate_prompt:
      type: default_resp_generator # kag.solver.prompt.default.resp_generator.RespGenerator
  reflector:
    type: default_reflector # kag.solver.implementation.default_reflector.DefaultReflector
    llm_client: *chat_llm

#------------kag-solver configuration end----------------#

```
