### ISSUE TITLE
EXtractor时间太长啥原因

### ISSUE THREAD

**Issue by Dongyexixue** [OpenSPG/KAG#418]
### Search before asking

- [x] I had searched in the [issues](https://github.com/OpenSPG/KAG/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

提取时间太长啥原因

![Image](https://github.com/user-attachments/assets/c07f2728-1e19-4356-8dd2-0c7fcd79e69a)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by thundax-lyp** [comment]
增加build并发数。
```yaml
kag_builder_pipeline:
  num_threads_per_chain: 10
  num_chains: 4
```
