### ISSUE TITLE
[Bug] [Module Name] Bug title

### ISSUE THREAD

**Issue by fishfish123-win** [OpenSPG/KAG#437]
### Search before asking

- [x] I had searched in the [issues](https://github.com/OpenSPG/KAG/issues?q=is%3Aissue) and found no similar issues.

### Operating system information

Linux

### What happened

现在想创建.md格式的开发者模式下的知识库

### How to reproduce

就是复制了baike 下面的config，更改了一下里面的reader，改为了 md_reader，但是一直生成不成功

![Image](https://github.com/user-attachments/assets/62da91be-142a-4ead-ab5a-f4a4e925c05a)

![Image](https://github.com/user-attachments/assets/b29df34f-693b-4ef4-877f-392b96cb418c)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by thundax-lyp** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/OpenSPG/KAG/issues?q=is%3Aissue) and found no similar issues.
> 
> ### Operating system information
> Linux
> 
> ### What happened
> 现在想创建.md格式的开发者模式下的知识库
> 
> ### How to reproduce
> 就是复制了baike 下面的config，更改了一下里面的reader，改为了 md_reader，但是一直生成不成功
> 
> ![Image](https://github.com/user-attachments/assets/62da91be-142a-4ead-ab5a-f4a4e925c05a)
> 
> ![Image](https://github.com/user-attachments/assets/b29df34f-693b-4ef4-877f-392b96cb418c)
> 
> ### Are you willing to submit PR?
> * [ ]  Yes I am willing to submit a PR!

试试给scanner加个参数。
```yaml
kag_builder_pipeline:
  scanner:
    type: dir_file_scanner # kag.builder.component.scanner.directory_scanner.DirectoryScanner
    file_suffix: md
```
