### ISSUE TITLE
temperature 温度问题

### ISSUE THREAD

**Issue by BQQQQB** [OpenSPG/KAG#446]
0.6版本不能自定义模型温度了吗？或者在哪里可以设置，感谢告知

**Comment by thundax-lyp** [comment]
> 0.6版本不能自定义模型温度了吗？或者在哪里可以设置，感谢告知
```yaml
generate_llm: &generate_llm
  base_url: {YOUR_BASE_URL}
  model: {YOUR_MODEL}
  temperature: 0.7
  type: maas
```
