### ISSUE TITLE
[Bug] [Module Name] Bug title

### ISSUE THREAD

**Issue by Reuspect** [OpenSPG/KAG#488]
### Search before asking

- [x] I had searched in the [issues](https://github.com/OpenSPG/KAG/issues?q=is%3Aissue) and found no similar issues.

### Operating system information

Linux

### What happened

I was running the riskmining project. When I followed README-cn.md to the final step and executed python qa.py, an error occurred. After taking a look, it seemed that in the default configuration of kag_config.yaml of this project, there was a ner_prompt setting a value that was not in the options. If set to the values in the options of the error message, it seems that the process can be executed normally. maybe the default value should be changed to "default_ner"?

![Image](https://github.com/user-attachments/assets/e9e671f8-c841-4c09-9d0f-fa2d2111cf47)

![Image](https://github.com/user-attachments/assets/360c24d4-50d2-455b-9d2b-ce4e84fd381e)

### How to reproduce

run riskmining program and follow the steps until final step: python qa.py, then it reproduces.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by thundax-lyp** [comment]
this is a bad config. 
download the latest code(it is necessary, some bugs has been fixed just a moment before)
remove ner_prompt from config.yaml, such as
```
kg_fr:
  type: kg_fr_open_spg
  top_k: 20
  path_select:
    type: fuzzy_one_hop_select
    llm_client: *chat_llm
  ppr_chunk_retriever_tool:
    type: ppr_chunk_retriever
    llm_client: *openie_llm
    ner:
      type: ner
      llm_module: *openie_llm
  entity_linking:
    type: entity_linking
    recognition_threshold: 0.8
    exclude_types:
      - Chunk

```
