### ISSUE TITLE
[Bug] [Solver] Missing definition for prompt 'default_iterative_planning'

### ISSUE THREAD

**Issue by thundax-lyp** [OpenSPG/KAG#559]
### Search before asking

- [x] I had searched in the [issues](https://github.com/OpenSPG/KAG/issues?q=is%3Aissue) and found no similar issues.

### Operating system information

Linux

### What happened

在测试文件 ```/tests/unit/executor/kag_config.yaml``` 中的 ```iterative_solver_pipeline``` 定义了叫```default_iterative_planning```的prompt，但是在项目中没有找到该prompt的定义文件

```yaml
iterative_solver_pipeline:
  type: kag_iterative_pipeline
  planner:
    type: kag_iterative_planner
    llm: *openie_llm
    plan_prompt:
      type: default_iterative_planning
```

### How to reproduce

rerun test case in ```/tests/unit/executor/```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
